name: XNL
on: [workflow_dispatch]

jobs:
  XML:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3

      - name: Build
        run: dotnet build

      - name: Run
        run: |
          cd diagram/bin/Debug/net6.0
          dotnet diagram.dll  

      - name: Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: XML
          path: |
            ./diagram/bin/Debug/net6.0/Animal.xml
            ./diagram/bin/Debug/net6.0/Lion.xml

